init
EkimEvgeny/backuper pull request #1
Opened 2022-11-03 10:28 UTC by confa-hub

init project

2022-11-07 11:24 UTC, EkimEvgeny requested changes

2022-11-07 11:24 UTC, EkimEvgeny commented on .idea/.gitignore
> +# Default ignored files
Папку .idea не нужно коммитить

2022-11-07 11:24 UTC, EkimEvgeny commented on config-application.json
> +    "databaseSaveToTmp": "E:/node.js/Dev/creator-backup-copies/src/tmp/BackupDataBase.backup"
Зачем два почти одинаковых параметра нужны "directoryTMPPath" и "databaseSaveToTmp"? Если причин существенных нет, то нужно сделать один параметр "tempDirectoryPath" и указывать путь к папке, где будут храниться временные файлы.

2022-11-07 11:24 UTC, EkimEvgeny commented on package.json
> +    "nodejs-zip": "^0.1.0",
Лишняя библиотека. Нужно удалить

2022-11-07 11:24 UTC, EkimEvgeny commented on package.json
> +    "file-saver": "^2.0.5",
Используется ли эта библиотека? Если нет, то нужно удалить. Если да, то нужно объяснить зачем?

2022-11-07 11:24 UTC, EkimEvgeny commented on package.json
> +    "@nestjs/axios": "^0.1.0",
Нужно удалить

2022-11-07 11:24 UTC, EkimEvgeny commented on package.json
> +    "axios": "^1.1.3",
Нужно удалить

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +  private obj: any;
Что это за переменная? Почему тип any? (должен быть конкретный тип данных). К переменным-полям классов обязательно нужны комментарии.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +  differenceTIme: number = 1;
Написано неправильно - должно быть differenceTime. Также по смыслу не совсем правильно и не дает понимания, зачем эта переменная нужна. Логичнее было  назвать ее как-то вроде "firstBackupDelay". Непонятно, почему это число, и почему оно устанавливается в 1 - нужно расписать в комментарии.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    const data = fs.readFileSync("E:/node.js/Dev/creator-backup-copies/config-application.json", "utf8");
Здесь должен стоять относительный путь. Так будет работать только на твоем компьютере.  В программе, вообще, нигде нельзя использовать полные пути. Полные пути только в конфигах.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    const data = fs.readFileSync("E:/node.js/Dev/creator-backup-copies/config-application.json", "utf8");
Название переменной должно отражать, что эта переменная хранит. Здесь нормально подойдет "configData" или подобное

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +  differenceTIme: number = 1;
Также непонятно, зачем эта переменная объявлена как поле класса, а не инициализируется и используется только в методе инициализации. Нужно ее оставить только в методе класса.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +
Лишний отступ

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    this.obj = JSON.parse(data);
Название переменное должно отражать, что это такое

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +
Лишний отступ

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    const logFile = this.obj["logFile"];
Название должно быть понятнее. Здесь понятнее будет logFilePath

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    this.differenceTIme = this.fileService.lastDateBackupDifference(logFile, this.numberOfTimes());
Где используется эта переменная? Вроде бы нигде. Работает ли сейчас создание первого бэкапа после запуска программы?

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    }, 2);
Почему стоит интервал 2?

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +   * Создан чтобы убрать дублирования кода
Писать комментарии, что метод нужен для того, чтобы убрать дублирование кода не нужно. Все методы нужны только для того, чтобы код не дублировать.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +  private async fileOperations(pathsFileForArchive, zip) {
Из названия метода непонятно, что он делает. Нормально было бы что-то вроде "createFullBackup" или наподобии.
pathsFileForArchive - по-английски очень криво написано. Нужно filePathsForArchive или archiveFilePaths

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    let times = this.obj["backup_frequency"];
Название параметра backup_frequency должно быть без подчеркивания

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +    const number = 86400000 / this.obj["backup_frequency"];
Константу 864000000 лучше разбить на несколько, например 60 * 60 * 24 * 1000 - так намного понятнее, что это за число. У переменной должно быть осмысленное название.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/app.service.ts
> +  numberOfTimes(): number {
У функции должно быть осмысленное название, которое соответствует тому, что эта функция делает

2022-11-07 11:24 UTC, EkimEvgeny commented on src/file-manager/dto/fileBackup.dto.ts
> +export class FileBackup{
Нет комментариев у полей класса.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/file-manager/file-manager.module.ts
> +export class FileManagerModule {}
Нет комментария у класса.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +
Убрать пустые строки

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +      let data = fs.readFileSync('E:/node.js/Dev/creator-backup-copies/config-application.json', 'utf8');
Нельзя использовать абсолютные пути!!!

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +  async isFolderYandexDisk(): Promise<boolean> {
Из коммента непонятно существование какой папки проверяется. Соответственно и название метода непонятное.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +      const directoryTMPPath = configApplication[`directoryTMPPath`]
Зачем здесь эта константа, если она не используется?

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +      return false;
Если выдалось исключение, то его нужно, как минимум записать в консоль или лог.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +      let data = fs.readFileSync('E:/node.js/Dev/creator-backup-copies/config-application.json', 'utf8');
Нельзя использовать абсолютные пути!!!

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +      const configApplication = JSON.parse(data);
Должен быть модуль и сервис конфигурации, в котором парсинг файла будет просходить только при инициализации сервиса.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +      console.error("Ошибка ==== " + error);
нужно посмотреть, как делаются логи в nestJS и везде использовать логирование, как в nestJS. https://docs.nestjs.com/techniques/logger

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +    let data = fs.readFileSync('E:/node.js/Dev/creator-backup-copies/config-application.json', 'utf8');
Абсолютные пути в программе под запретом!!!

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +   * Медор использует Множество действий (Создание папки и отправку файла)
Из коммента непонятно, что конкретно делает файл. Из названия непонятно, что именно загружает этот метод.

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +    this.folder = dayjs().format("YYYY-MM-DD HH:mm");
название папки не может включать в себя двоеточие. Формат даты не русский. Нормально будет иметь формат "DD.MM.YYYY-HH mm".

2022-11-07 11:24 UTC, EkimEvgeny commented on src/yandex-disk/services/yandex-disk.service.ts
> +      const timeFileBackup = dayjs().format("YYYY-MM-DD HH:mm");
название файла не может включать в себя двоеточие. Формат даты не русский. Нормально будет иметь формат "DD.MM.YYYY-HH mm

2022-11-07 11:24 UTC, EkimEvgeny commented on src/zip-input-stream/zip-input-stream.module.ts
> +export class ZipInputStreamModule {}
Нет комментария у класса

2022-11-07 11:24 UTC, EkimEvgeny commented on src/zip-input-stream/services/zip-input-stream.service.ts
> +  async backupDataBase(){
Непонятно, какое отношение этот метод имеет к этому классу. Нужно перенести его в более уместное место.

2022-11-07 11:24 UTC, EkimEvgeny commented on config-application.json
> +  "backup_frequency" : 23,
Название параметра должно быть без подчеркивания

2022-11-07 11:24 UTC, EkimEvgeny commented on package.json
> +    "async-lock": "^1.4.0",
Вроде, библиотека не используется. Если так, то нужно удалить.

2022-11-07 11:24 UTC, EkimEvgeny commented on package.json
> +    "zip-dir": "^2.0.0"
Вроде библиотека не используется. Если так, то нужно удалить.

2022-11-08 07:54 UTC, confa-hub commented on .idea/.gitignore
> +# Default ignored files
Исправлено

2022-11-08 07:54 UTC, confa-hub commented on config-application.json
> +    "databaseSaveToTmp": "E:/node.js/Dev/creator-backup-copies/src/tmp/BackupDataBase.backup"
Исправлено

2022-11-08 07:54 UTC, confa-hub commented on package.json
> +    "nodejs-zip": "^0.1.0",
Исправлено

2022-11-08 07:54 UTC, confa-hub commented on package.json
> +    "file-saver": "^2.0.5",
Исправлено

2022-11-08 07:55 UTC, confa-hub commented on package.json
> +    "@nestjs/axios": "^0.1.0",
Исправлено

2022-11-08 07:55 UTC, confa-hub commented on package.json
> +    "axios": "^1.1.3",
Исправлено

2022-11-08 07:57 UTC, confa-hub commented on src/app.service.ts
> +  private obj: any;
Данная переменная переименована в configData. Тип данной переменной any потому что она инициализируется методом Json.parse который тоже возращает any.

2022-11-08 08:01 UTC, confa-hub commented on src/app.service.ts
> +  differenceTIme: number = 1;
Данная переменная переименована firstBackupDelay. Объявлена  в начале класса для использования в других методах и имеет default значение 1. Так же эта переменная инициализируется методом getNumberOfTimes.

2022-11-08 08:02 UTC, confa-hub commented on src/app.service.ts
> +    const data = fs.readFileSync("E:/node.js/Dev/creator-backup-copies/config-application.json", "utf8");
Исправлено

2022-11-08 08:02 UTC, confa-hub commented on src/app.service.ts
> +
Исправлено

2022-11-08 08:03 UTC, confa-hub commented on src/app.service.ts
> +    this.obj = JSON.parse(data);
Исправлено

2022-11-08 08:03 UTC, confa-hub commented on src/app.service.ts
> +
Исправлено

2022-11-08 08:03 UTC, confa-hub commented on src/app.service.ts
> +    const logFile = this.obj["logFile"];
Исправлено

2022-11-08 08:03 UTC, confa-hub commented on src/app.service.ts
> +    this.differenceTIme = this.fileService.lastDateBackupDifference(logFile, this.numberOfTimes());
Исправлено

2022-11-08 08:03 UTC, confa-hub commented on src/app.service.ts
> +    }, 2);
Исправлено

2022-11-08 08:04 UTC, confa-hub commented on src/app.service.ts
> +   * Создан чтобы убрать дублирования кода
Исправлено

2022-11-08 08:04 UTC, confa-hub commented on src/app.service.ts
> +  private async fileOperations(pathsFileForArchive, zip) {
Исправлено

2022-11-08 08:04 UTC, confa-hub commented on src/app.service.ts
> +    let times = this.obj["backup_frequency"];
Исправлено

2022-11-08 08:04 UTC, confa-hub commented on src/app.service.ts
> +    const number = 86400000 / this.obj["backup_frequency"];
Исправлено

2022-11-08 08:06 UTC, confa-hub commented on src/file-manager/dto/fileBackup.dto.ts
> +export class FileBackup{
Исправлено

2022-11-08 08:07 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +
Исправлено

2022-11-08 08:07 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +      let data = fs.readFileSync('E:/node.js/Dev/creator-backup-copies/config-application.json', 'utf8');
Исправлено

2022-11-08 08:08 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +  async isFolderYandexDisk(): Promise<boolean> {
Исправлено

2022-11-08 08:08 UTC, confa-hub commented on src/file-manager/file-manager.module.ts
> +export class FileManagerModule {}
Исправлено

2022-11-08 08:14 UTC, confa-hub commented on src/app.service.ts
> +  numberOfTimes(): number {
Исправлено

2022-11-08 12:45 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +      const directoryTMPPath = configApplication[`directoryTMPPath`]
Исправлено

2022-11-08 12:47 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +    let data = fs.readFileSync('E:/node.js/Dev/creator-backup-copies/config-application.json', 'utf8');
Исправлено

2022-11-08 12:51 UTC, confa-hub commented on src/zip-input-stream/zip-input-stream.module.ts
> +export class ZipInputStreamModule {}
Исправлено

2022-11-08 12:51 UTC, confa-hub commented on src/zip-input-stream/services/zip-input-stream.service.ts
> +  async backupDataBase(){
Исправлено

2022-11-08 12:51 UTC, confa-hub commented on config-application.json
> +  "backup_frequency" : 23,
Исправлено

2022-11-08 12:51 UTC, confa-hub commented on package.json
> +    "async-lock": "^1.4.0",
Исправлено

2022-11-08 12:52 UTC, confa-hub commented on package.json
> +    "zip-dir": "^2.0.0"
Исправлено

2022-11-09 09:25 UTC, confa-hub commented on src/app.service.ts
> +  private obj: any;
Переменная удалена

2022-11-09 09:26 UTC, confa-hub commented on src/app.service.ts
> +  private obj: any;
Исправлено

2022-11-09 09:27 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +      return false;
Исправлено

2022-11-09 09:27 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +      let data = fs.readFileSync('E:/node.js/Dev/creator-backup-copies/config-application.json', 'utf8');
Исправлено

2022-11-09 09:27 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +      const configApplication = JSON.parse(data);
Исправлено

2022-11-09 09:28 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +      console.error("Ошибка ==== " + error);
Исправлено

2022-11-09 09:29 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +   * Медор использует Множество действий (Создание папки и отправку файла)
Исправлено

2022-11-09 09:31 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +    this.folder = dayjs().format("YYYY-MM-DD HH:mm");
Исправлено

2022-11-09 09:31 UTC, confa-hub commented on src/yandex-disk/services/yandex-disk.service.ts
> +      const timeFileBackup = dayjs().format("YYYY-MM-DD HH:mm");
Исправлено

2024-05-15 14:18 UTC, merged